version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - uploads:/app/uploads
      - db:/app/db
    env_file:
      - ../.env

volumes:
  uploads:
  db: