version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - uploads:/app/uploads
    env_file:
      - ../.env
    depends_on:
      - database
    networks:
      - api-network

  database:
    image: postgres:latest
    restart: always
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pmv4
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - api-network

networks:
  api-network:

volumes:
  uploads:
  pg_data: